### ISSUE TITLE
Vanillatweaks 3d trapdoor model lets one x-ray

### ISSUE THREAD

**Issue by MeeniMc** [FxMorin/MoreCulling#125]
See trap door in the center. Defect not present with all same setup except removal of MoreCulling

![2022-12-31_15 50 57](https://user-images.githubusercontent.com/68366846/210155470-8ab1a34d-364b-4daa-8951-70bfcdc776ee.png)

moreculling-1.19.3-0.12.3
sodium-fabric-mc1.19.3-0.4.7+build.21

```
Vanilla Tweaks Resource Pack
Version: 1.19
Packs:
	DoubleSlabFix
	ItemHoldFix
	PixelConsistentGhast
	PixelConsistentElderGuardian
	PixelConsistentWither
	ItemStitchingFix
	LiteralGameruleNames
	3DBookshelves
	3DChains
	3DPointedDripstone
	3DAmethyst
	3DTiles
	3DLadders
	3DRails
	3DIronBars
	3DLilyPads
	3DTrapdoors
	3DMushrooms
	3DStonecutters
	3DSunMoon
	3DSugarcane
	3DDoors
	CleanStainedGlass
	CleanTintedGlass
	CleanGlass
	AlternateEnchantGlint
	LowerFire
	LowerShield
	TransparentPumpkin
	NoVignette
	SmallerUtilities
	BuddingAmethystBorders
	VisualInfestedStoneItems
	VisualWaxedCopperItems
	GroovyLevers
	ClearBannerPatterns
	VariatedDirt
	RandomCoarseDirtRotation
	VariatedGrass
	VariatedCobblestone
	RandomMossRotation
	VariatedBricks
	VariatedPlanks
	VariatedMycelium
	VariatedGravel
	VariatedEndStone
	VariatedMushroomBlocks
	VariatedLogs
	VariatedStone
	VariatedTerracotta
	VariatedUnpolishedStones
	CircleLogTops
	FancySunflowers
	ShorterGrass
	ShorterTallGrass
	BetterBedrock
	HDShieldBanners
	UniqueDyes
	AshlessCampfires
	SplashXpBottle
	GoldenCrown
	EnderDragonElytra
	RedIronGolemFlowers
	NoSpyglassOverlay
	AccurateSpyglass

Combined packs:
	AccurateSpyglass+NoSpyglassOverlay
```

**Comment by fxmorin** [comment]
I'm not exactly sure why this happens, although I believe its due to the 3D model no longer following the internal cull shape of the block. This is probably not something that vanillatweaks should be doing

**Comment by fxmorin** [comment]
I'll probably add conditions for custom models in the next major release. Not sure yet, however you can disable blockstate culling in the settings to temporarily fix this

**Comment by DmanMC** [comment]
also happens with 3d glow lichen

**Comment by fxmorin** [comment]
Alright in v0.15.0 its now possible to fix this!
https://github.com/fxmorin/MoreCulling/wiki/Resource-Packs

**Comment by MeeniMc** [comment]
Issue has been resolved with newer VT pack that makes trapdoors thicker.

**Comment by Naidrox** [comment]
Just ran into this myself today. I'll post a proper issue when I have a bit more time

**Comment by mpustovoi** [comment]
I still have this issue with v0.22.1 for Fabric 1.20.1 and the newest VT 3D trapdoors (just downloaded the latest)
![image](https://github.com/FxMorin/MoreCulling/assets/92390626/97ee809a-cbee-4c60-967c-5adba8067d24)
Maybe I should toggle something in config, idk

**Comment by FxMorin** [comment]
Im working on a fix

**Comment by FxMorin** [comment]
Lets keep this closed, the issue is now being followed by: https://github.com/FxMorin/MoreCulling/issues/225
