### ISSUE TITLE
see though underground when open the shulkerbox

### ISSUE THREAD

**Issue by cloudy1552** [fxmorin/MoreCulling#126]
when i open the shulkerboxes, i can see though underground from the side of shulkerbox. this usually happens when i put them in the coner surrounded by fullblocks(like L shape or O shape). please fix this or add the config that disables blockstate culling of shulkerboxes.

**Comment by fxmorin** [comment]
Fixed in v0.12.5

**Comment by cloudy1552** [comment]
im using 0.12.5 but still see though.
![2023-01-06_19 15 33](https://user-images.githubusercontent.com/121796704/210982867-4373fcc5-5299-4483-805c-5fd5af78364c.png)
when i turn off blockstate culling, this didnt happend.
im sorry to bothering you again.
