### ISSUE TITLE
Crash with new version of modernfix 5.10.1

### ISSUE THREAD

**Issue by lostopkk** [FxMorin/MoreCulling#195]
https://github.com/embeddedt/ModernFix/issues/319#event-11225107062

**Comment by DroidZed** [comment]
Many users have been facing this exact same issue, any news about the matter ? No pressure of course.

**Comment by FxMorin** [comment]
Should be fixed in the next release

**Comment by NolanHewitt** [comment]
Still crashes with the new 0.21.0 version for me.

**Comment by FxMorin** [comment]
@NolanHewitt Can you give me logs?

**Comment by FxMorin** [comment]
Fixed in [v0.22.0](https://github.com/FxMorin/MoreCulling/releases/tag/v0.22.0-1.20.1%2B)

**Comment by SettingDust** [comment]
Crash not sure whether relate to this issue with 0.22.0 on 1.20.1 fabric

Dev
```
 java.lang.NullPointerException: Cannot invoke "java.util.Map.getOrDefault(Object, Object)" because "this.bakedRegistry" is null
	at net.minecraft.client.resources.model.ModelManager.getModel(ModelManager.java:83) ~[minecraft-merged-40d78413b1-1.20.1-loom.mappings.1_20_1.layered+hash.1851035355-v2.jar:?]
	at net.minecraft.client.renderer.block.BlockModelShaper.cacheBlockModel(BlockModelShaper.java:1040) ~[minecraft-merged-40d78413b1-1.20.1-loom.mappings.1_20_1.layered+hash.1851035355-v2.jar:?]
	at net.minecraft.client.renderer.block.BlockModelShaper.md3a2172$modernfix$lambda$new$0$1(BlockModelShaper.java:1027) ~[minecraft-merged-40d78413b1-1.20.1-loom.mappings.1_20_1.layered+hash.1851035355-v2.jar:?]
	at it.unimi.dsi.fastutil.Function.apply(Function.java:93) ~[fastutil-8.5.9.jar:?]
	at org.embeddedt.modernfix.dynamicresources.DynamicModelCache.cacheModel(DynamicModelCache.java:52) ~[modernfix-5.12.1_mc1.20.1.jar:?]
	at org.embeddedt.modernfix.dynamicresources.DynamicModelCache.get(DynamicModelCache.java:74) ~[modernfix-5.12.1_mc1.20.1.jar:?]
	at net.minecraft.client.renderer.block.BlockModelShaper.getBlockModel(BlockModelShaper.java:1054) ~[minecraft-merged-40d78413b1-1.20.1-loom.mappings.1_20_1.layered+hash.1851035355-v2.jar:?]
	at net.minecraft.client.renderer.block.BlockRenderDispatcher.getBlockModel(BlockRenderDispatcher.java:111) ~[minecraft-merged-40d78413b1-1.20.1-loom.mappings.1_20_1.layered+hash.1851035355-v2.jar:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase$Cache.redirect$ljl000$moreculling$shouldDoShapeCache(BlockBehaviour.java:2767) ~[minecraft-merged-40d78413b1-1.20.1-loom.mappings.1_20_1.layered+hash.1851035355-v2.jar:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase$Cache.<init>(BlockBehaviour.java:852) ~[minecraft-merged-40d78413b1-1.20.1-loom.mappings.1_20_1.layered+hash.1851035355-v2.jar:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.initCache(BlockBehaviour.java:459) ~[minecraft-merged-40d78413b1-1.20.1-loom.mappings.1_20_1.layered+hash.1851035355-v2.jar:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.mfix$generateCache(BlockBehaviour.java:2439) ~[minecraft-merged-40d78413b1-1.20.1-loom.mappings.1_20_1.layered+hash.1851035355-v2.jar:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.redirect$dfi000$modernfix$dynamicCacheGen(BlockBehaviour.java:2458) ~[minecraft-merged-40d78413b1-1.20.1-loom.mappings.1_20_1.layered+hash.1851035355-v2.jar:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.isSolidRender(BlockBehaviour.java:592) ~[minecraft-merged-40d78413b1-1.20.1-loom.mappings.1_20_1.layered+hash.1851035355-v2.jar:?]
	at me.pepperbell.continuity.client.resource.CustomBlockLayers.getLayer(CustomBlockLayers.java:45) ~[continuity-3.0.0_beta.4_1.20.1.jar:?]
	at net.minecraft.client.renderer.ItemBlockRenderTypes.handler$eao000$continuity$onHeadGetBlockLayer(ItemBlockRenderTypes.java:1019) ~[minecraft-merged-40d78413b1-1.20.1-loom.mappings.1_20_1.layered+hash.1851035355-v2.jar:?]
	at net.minecraft.client.renderer.ItemBlockRenderTypes.getChunkRenderType(ItemBlockRenderTypes.java) ~[minecraft-merged-40d78413b1-1.20.1-loom.mappings.1_20_1.layered+hash.1851035355-v2.jar:?]
	at fuzs.puzzleslib.impl.client.core.FabricClientAbstractions.getRenderType(FabricClientAbstractions.java:40) ~[puzzleslib-8.1.13.jar:8.1.13]
	at fuzs.diagonalblocks.client.DiagonalBlocksClient.lambda$registerHandlers$0(DiagonalBlocksClient.java:49) ~[diagonalblocks-8.0.3.jar:8.0.3]
	at fuzs.puzzleslib.impl.client.event.FabricClientEventInvokers.lambda$register$1(FabricClientEventInvokers.java:80) ~[puzzleslib-8.1.13.jar:8.1.13]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:35) ~[fabric-lifecycle-events-v1-2.2.21_b3afc78b77.jar:?]
	at net.minecraft.client.Minecraft.handler$njk001$fabric-lifecycle-events-v1$onStart(Minecraft.java:377) ~[minecraft-merged-40d78413b1-1.20.1-loom.mappings.1_20_1.layered+hash.1851035355-v2.jar:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:696) ~[minecraft-merged-40d78413b1-1.20.1-loom.mappings.1_20_1.layered+hash.1851035355-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:229) ~[minecraft-merged-40d78413b1-1.20.1-loom.mappings.1_20_1.layered+hash.1851035355-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
```
Prod
```
java.lang.NullPointerException: Cannot invoke "java.util.Map.getOrDefault(Object, Object)" because "this.models" is null
	at net.minecraft.client.render.model.BakedModelManager.getModel(BakedModelManager.java:71) ~[client-intermediary.jar:?]
	at net.minecraft.client.render.block.BlockModels.cacheBlockModel(BlockModels.java:1540) ~[client-intermediary.jar:?]
	at net.minecraft.client.render.block.BlockModels.md01702d$modernfix$lambda$new$0$1(BlockModels.java:1527) ~[client-intermediary.jar:?]
	at it.unimi.dsi.fastutil.Function.apply(Function.java:93) ~[fastutil-8.5.9.jar:?]
	at org.embeddedt.modernfix.dynamicresources.DynamicModelCache.cacheModel(DynamicModelCache.java:52) ~[modernfix-fabric-5.12.1+mc1.20.1.jar:?]
	at org.embeddedt.modernfix.dynamicresources.DynamicModelCache.get(DynamicModelCache.java:74) ~[modernfix-fabric-5.12.1+mc1.20.1.jar:?]
	at net.minecraft.client.render.block.BlockModels.getModel(BlockModels.java:1554) ~[client-intermediary.jar:?]
	at net.minecraft.client.render.block.BlockRenderManager.getModel(BlockRenderManager.java:90) ~[client-intermediary.jar:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState$AbstractBlockState$ShapeCache.redirect$lkm000$moreculling$shouldDoShapeCache(AbstractBlock.java:2390) ~[client-intermediary.jar:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState$AbstractBlockState$ShapeCache.<init>(AbstractBlock.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.initShapeCache(AbstractBlock.java:843) ~[client-intermediary.jar:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.mfix$generateCache(AbstractBlock.java:6370) ~[client-intermediary.jar:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.redirect$lhi000$modernfix$dynamicCacheGen(AbstractBlock.java:6389) ~[client-intermediary.jar:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.isOpaqueFullCube(AbstractBlock.java:1009) ~[client-intermediary.jar:?]
	at me.pepperbell.continuity.client.resource.CustomBlockLayers.getLayer(CustomBlockLayers.java:45) ~[continuity-3.0.0-beta.4+1.20.1.jar:?]
	at net.minecraft.client.render.RenderLayers.handler$heg000$continuity$onHeadGetBlockLayer(RenderLayers.java:1519) ~[client-intermediary.jar:?]
	at net.minecraft.client.render.RenderLayers.getBlockLayer(RenderLayers.java) ~[client-intermediary.jar:?]
	at fuzs.puzzleslib.impl.client.core.FabricClientAbstractions.getRenderType(FabricClientAbstractions.java:40) ~[PuzzlesLib-v8.1.13-1.20.1-Fabric.jar:?]
	at fuzs.diagonalblocks.client.DiagonalBlocksClient.lambda$registerHandlers$0(DiagonalBlocksClient.java:49) ~[diagonalblocks-8.0.3-f633d15a2524fa82.jar:?]
	at fuzs.puzzleslib.impl.client.event.FabricClientEventInvokers.lambda$register$1(FabricClientEventInvokers.java:80) ~[PuzzlesLib-v8.1.13-1.20.1-Fabric.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:35) ~[fabric-lifecycle-events-v1-2.2.2+b3afc78b77-5394548d5b576a28.jar:?]
	at net.minecraft.client.MinecraftClient.handler$ccg000$fabric-lifecycle-events-v1$onStart(MinecraftClient.java:12554) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.5.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
```

**Comment by NolanHewitt** [comment]
Unfortunately still crashes on 0.22.0 for me. Logs are here.
https://gist.github.com/NolanHewitt/c8bdc71ffb7619bf27b4a31a08c25a13
https://gist.github.com/NolanHewitt/00011b8bf53245fa42c5afa6cf49c583

**Comment by FxMorin** [comment]
Are you using the latest version of ModernFix?

**Comment by lostopkk** [comment]
![image](https://github.com/FxMorin/MoreCulling/assets/50776714/03d5c2dc-5428-46eb-bd03-fdc9732cbd29)

yes, he is using it, it was in his log. @FxMorin

**Comment by NolanHewitt** [comment]
Yeah, modern fix 5.12.1 and More Culling 0.22.0 were the versions I was using.

That being said, perhaps this has something to do with continuity? When I remove that mod I can launch with both more culling and dynamic resources from modernfix. Continuity's own built in resource pack is also broken so perhaps that mod is just funky?
