### ISSUE TITLE
Cull shapes dynamically for resource packs

### ISSUE THREAD

**Issue by Madis0** [FxMorin/MoreCulling#225]
> Might look into some sort of setup which makes cull shapes dynamically for non-mc packs.
> I have a way for resource packs to fix this, but its prob better if I handle it
> Ill try to find some time to fix it
`- FX`

**Comment by JosefLitos** [comment]
This issue started to occur again since 0.21.0 - no xray on trapdoors in 0.20.3, now:
![obrazek](https://github.com/FxMorin/MoreCulling/assets/54900518/c2a5a626-444d-4a41-b5e7-4970af5d2ec3)

**Comment by Obscure2020** [comment]
A user in the VanillaXBR Discord server has recently brought a More Culling issue to our attention. It appears that More Culling is over-agressively culling faces of blocks behind trapdoors, allowing you to see through the block through the hole in the trapdoor. This only happens on Jungle, Mangrove, and Cherry trapdoors. It only happens when using the VanillaXBR resource pack (deactivating the pack to use the built-in vanilla textures removes the bug). It also only happens when BlockState Culling is turned on. Is this related to this same issue, or should I open a new issue?

**Comment by JosefLitos** [comment]
Yes, that is exactly the matter of this issue. You can suggest trying the 0.20.3 version, it helped in my case.

**Comment by Obscure2020** [comment]
You were exactly right! I went back and checked each version going backwards. In v0.22.1, v0.22.0, and v0.21.0, the trapdoors render like this:

![broken slice](https://github.com/FxMorin/MoreCulling/assets/69320464/6f88ca48-42e1-46e7-aa7b-3f8c015733c3)

Going all the way back to v0.20.3, the bug disappears:

![healthy slice](https://github.com/FxMorin/MoreCulling/assets/69320464/92d01011-e0be-4cbc-ae2d-c0423a8579ab)

**Comment by Obscure2020** [comment]
The part that confuses me is why this affects only some trapdoors in the resource pack and not others? I inspected the files in the pack very carefully and I can't find anything that sets the Jungle, Mangrove, and Cherry trapdoors apart from the others.

**Comment by thebertster** [comment]
It has been suggested that all that is needed to fix this currently is to add useModelShape: true to the models in the resource pack (https://github.com/fxmorin/MoreCulling/wiki/Resource-Packs) however I have made this modification to the VanillaTweaks 3D trapdoor models and it has not changed the behaviour. Only disabling the BlockState Culling option in MoreCulling resolves the issue for me (Fresh 1.20.4 MoreCulling 0.22.1 Fabric with no other mods or Resource Packs). I see the issue on all trapdoors that have transparent elements.

Here is one of the models that I modified (bamboo_trapdoor_top.json) - I modified all models (with a script) in the same way:

[bamboo_trapdoor_top.json](https://github.com/FxMorin/MoreCulling/files/14394712/bamboo_trapdoor_top.json)

**Comment by FxMorin** [comment]
Should be fixed in v0.23.0
Sorry for the wait, been too busy to work on mods recently

**Comment by JosefLitos** [comment]
No problem. Thank you for all the work you're putting into these mods. For me they are the reason I can use cool 3D model resourcepacks and not crush my laptop 😀.

**Comment by Lulu300** [comment]
I've just tested the version 0.23.1 with only fabric-api-0.97.0+1.20.4 and cloth-config-13.0.121-fabric and unfortunately with vanillatweaks 3D trapdoor the issue remain.

![image](https://github.com/FxMorin/MoreCulling/assets/12187295/856a2927-0dde-4ce4-8dcd-04b79f677163)

This issue must really be an annoying one to fix...

**Comment by thebertster** [comment]
I mentioned in my earlier comment that adding useModelShape: true to the models did not work for me with the VT 3D trapdoors.

I have only been able to work around it by removing all the cullface keys from the models, but this is I assume less than ideal.

There seems to be something more to this issue with VT 3D trapdoors.

**Comment by Lulu300** [comment]
Yeah thank you for reminding me, that for now i'll stick with the old v0.20.3. Unfortunately it seems that VT will not do anything on their part 
![image](https://github.com/FxMorin/MoreCulling/assets/12187295/54114690-4bff-4ac3-b19f-7e6188d03a89)

**Comment by FxMorin** [comment]
Ill need to find time to check, but im guessing that VT, isnt just using a normal model.

**Comment by TheRedstoneShark** [comment]
I'm having the exact same issue with another 3d doors resource pack, "[Door Tweaks](https://modrinth.com/resourcepack/door-tweaks)" (using 1.20.4)

I've found that for both Vanilla Tweaks and Door Tweaks: Grass Blocks, Podzol, Myceilium, Dirt, Rooted Dirt, Stone, Deepslate, Netherrack, and Sand are not affected by the rendering bug, you can't see through them. (Also, there are probably more I haven't tested.) Weird that these are the exceptions.
